#! /usr/bin/env sh

groupadd pwm
usermod -a -G pwm root
usermod -a -G pwm pi

echo "1" >> /sys/class/pwm/pwmchip0/export
chmod -R g+w /sys/class/pwm/pwmchip0/pwm1
chown -R :pwm /sys/class/pwm/pwmchip0/pwm1

echo "3" >> /sys/class/pwm/pwmchip0/export
chmod -R g+w /sys/class/pwm/pwmchip0/pwm3
chown -R :pwm /sys/class/pwm/pwmchip0/pwm3

echo "5" >> /sys/class/pwm/pwmchip0/export
chmod -R g+w /sys/class/pwm/pwmchip0/pwm5
chown -R :pwm /sys/class/pwm/pwmchip0/pwm5

echo "7" >> /sys/class/pwm/pwmchip0/export
chmod -R g+w /sys/class/pwm/pwmchip0/pwm7
chown -R :pwm /sys/class/pwm/pwmchip0/pwm7

